### ISSUE TITLE
in comment

### ISSUE THREAD

**Issue by RGooders** [InFamousDino/Hob-Bot#3]
![image](https://user-images.githubusercontent.com/66017248/107874841-4b4c0380-6ede-11eb-811c-82747f872b3c.png)

**Comment by InFamousDino** [comment]
amazing

**Comment by RGooders** [comment]
![image](https://user-images.githubusercontent.com/66017248/107874917-c9100f00-6ede-11eb-844c-97b7371e5692.png)

**Comment by InFamousDino** [comment]
no
